// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request
        ? input.headers
        : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get('Authorization') === `Bearer ${supabaseKey}`
    ) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);

    return fetch(input, {
      ...init,
      headers,
    });
  };
}

function getClientEnv(
  name: 'VITE_SUPABASE_URL' | 'VITE_SUPABASE_PUBLISHABLE_KEY',
): string | undefined {
  const value = import.meta.env[name];

  return typeof value === 'string' && value.trim()
    ? value
    : undefined;
}

function createSupabaseClient() {
  // Browser configuration must be provided through VITE_* variables
  // at build time. Server-only secrets are not used here.
  const SUPABASE_URL = getClientEnv('VITE_SUPABASE_URL');
  const SUPABASE_PUBLISHABLE_KEY = getClientEnv(
    'VITE_SUPABASE_PUBLISHABLE_KEY',
  );

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];

    const message =
      `Missing Supabase environment variable(s): ${missing.join(', ')}. ` +
      `Configure VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY ` +
      `in your Cloudflare build environment.`;

    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(
    SUPABASE_URL,
    SUPABASE_PUBLISHABLE_KEY,
    {
      global: {
        fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
      },
      auth: {
        storage: typeof window !== 'undefined' ? localStorage : undefined,
        persistSession: true,
        autoRefreshToken: true,
      },
    },
  );
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy(
  {} as ReturnType<typeof createSupabaseClient>,
  {
    get(_, prop, receiver) {
      if (!_supabase) {
        _supabase = createSupabaseClient();
      }

      return Reflect.get(_supabase, prop, receiver);
    },
  },
);
